### ISSUE TITLE
saran

### ISSUE THREAD

**Issue by saifoelloh** [solehudindt/doscom-birth-reminder#1]
klo bisa data jgn di expose gan, mending taruh dicloud ato gimana nanti tinggal diambil lewat koneksi ke server

**Comment by solehudindt** [comment]
> klo bisa data jgn di expose gan, mending taruh dicloud ato gimana nanti tinggal diambil lewat koneksi ke server

whoops kelupaan gan, terimakasih sudah diingatkan
